# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync OAI-Adapter
    endpoint: http://export.arxiv.org/oai2
#    endpoint: http://eprints.mminf.univie.ac.at/cgi/oai2
    max_runs: 100
    sleep_time: 60
    fromdate: 2012-09-12T12:00:00
    event_types: [create, update, delete]

##### Inventory Builder Implementations #####

# A dynamic builder that creates inventories at request time
# inventory_builder:
#     class: DynamicInventoryBuilder
#     uri_path: sitemap.xml

# A static builder that creates and writes inventories in given intervals
inventory_builder:
    class: StaticInventoryBuilder
    max_sitemap_entries: 100
    interval: 15
    uri_path: sitemap.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
changememory:
    class: DynamicChangeSet
    uri_path: changeset
    max_changes: 1000

##### Publisher implementations #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host