# The default ResourceSync OAI-Adapter configuration

##### Source Configuration #####

source:
    name: ResourceSync OAI-Adapter
    host: irc.wikimedia.org
    channel: en.wikipedia
    nick: simplewikibot
    ident: simplewikibot-ident
    realname: simplewikibot-realname
    event_types: [create, update, delete]

##### Inventory Builder Implementations #####

# A dynamic builder that creates inventories at request time
inventory_builder:
    class: DynamicInventoryBuilder
    uri_path: sitemap.xml

# A static builder that creates and writes inventories in given intervals
# inventory_builder:
#     class: StaticInventoryBuilder
#     max_sitemap_entries: 100
#     interval: 15
#     uri_path: sitemap.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
changememory:
    class: DynamicChangeSet
    uri_path: changeset.xml
    max_changes: 1000

# A static file-based change memory
# changememory:
#     class: StaticChangeSet
#     uri_path: changesets
#     uri_file: most_recent.xml
#     max_sitemap_entries: 100    
#     max_changes: 5

##### Publisher implementations #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host