# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync Simulator
    number_of_resources: 10000
    change_delay: 2
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1

##### Inventory Builder Implementations #####

# A dynamic builder that creates inventories at request time
# inventory_builder:
#     class: DynamicInventoryBuilder
#     uri_path: sitemap.xml

# A static builder that creates and writes inventories in given intervals
inventory_builder:
    class: StaticInventoryBuilder
    max_sitemap_entries: 1000
    interval: 15
    uri_path: sitemap.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
changememory:
    class: DynamicChangeSet
    uri_path: changeset
    max_changes: 1000

##### Publisher implementations #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host