version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)18s - %(levelname)6s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: resync-source.log
    mode: w
loggers:
  source:
    level: DEBUG
    handlers: [console]
    propagate: no
  inventory_builder:
    level: DEBUG
    handlers: [console]
    propagate: no
  sitemap:
    level: DEBUG
    handlers: [console]
    propagate: no
  http:
    level: DEBUG
    handlers: [console]
    propagate: no
  changememory:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
