# The default ResourceSync Wikipedia-Adapter configuration

##### Source Configuration #####

source:
    name: ResourceSync OAI-Adapter
    host: irc.wikimedia.org
    channel: en.wikipedia
    nick: simplewikibot1
    ident: simplewikibot-ident1
    realname: simplewikibot-realname1
    event_types: [create, update, delete]
    dump_file: http://dumps.wikimedia.org/enwiki/latest/enwiki-latest-all-titles-in-ns0.gz
    uri_host: http://en.wikipedia.org/wiki


##### Inventory Builder Implementations #####

# A dynamic builder that creates inventories at request time
# inventory_builder:
#     class: DynamicInventoryBuilder
#     uri_path: sitemap.xml

# A static builder that creates and writes inventories in given intervals
inventory_builder:
    class: StaticInventoryBuilder
    max_sitemap_entries: 1000
    interval: 1800
    uri_path: sitemap.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
# changememory:
#     class: DynamicChangeSet
#     uri_path: changeset.xml
#     max_changes: 1000

# A static file-based change memory
changememory:
    class: StaticChangeSet
    uri_path: changesets
    uri_file: most_recent.xml
    max_sitemap_entries: 50
    max_changes: 50

##### Publisher implementations #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host
