# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync OAI-Adapter
    endpoint: http://eprints.cs.univie.ac.at/cgi/oai2
    max_runs: 100
    sleep_time: 30
    delay_time: 3
    fromdate: 2010-08-22T10:00:00
    event_types: [create, update, delete]

##### Inventory Builder Implementations #####

# A dynamic builder that creates inventories at request time
# inventory_builder:
#     class: DynamicInventoryBuilder
#     uri_path: sitemap.xml

# A static builder that creates and writes inventories in given intervals
inventory_builder:
    class: StaticInventoryBuilder
    max_sitemap_entries: 50000
    interval: 3600
    uri_path: sitemap.xml

##### ChangeMemory Implementations #####

# A dynamic memory-based change memory
# changememory:
#     class: DynamicChangeSet
#     uri_path: changeset.xml
#     max_changes: 1000

# A static file-based change memory
changememory:
    class: StaticChangeSet
    uri_path: changesets
    uri_file: most_recent.xml
    max_sitemap_entries: 10000
    max_changes: 10000

##### Publisher implementations #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host